version: "3.5"
services:
  api:
    image: flask_api
    container_name: quote_api
    build:
      context: ./quote-api
    ports:
      - "80:5000"
    environment:
      FLASK_APP: app
      FLASK_DEBUG: 1
    depends_on:
      - postgresql
    volumes:
      - ./quote-api/:/src/
  
  postgresql:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_USER: admin  # Your database user
      POSTGRES_PASSWORD: secret_pass # Your database password
      POSTGRES_DB: bookairfreight # Your database name
    volumes: 
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "54323:5432" # To allow connections from outside the container for development purposes